### ISSUE TITLE
Internal Server Error (HTTP 500) when updating a contest

### ISSUE THREAD

**Issue by ion-oset** [TrustTheVote-Project/VersaEDM-Backend#11] opened 2021-12-09 03:47 UTC
**HTTP request**: `PUT /contests/con_Orbit_City_Mayoral`
**Exception**:
```
    File "src/electos/versadm/app/routers/common.py", line 14, in wrapped
    func_result = func(*args, **kwargs)
  File "src/electos/versadm/app/routers/contest.py", line 50, in update_contest
    if existing_record.obj_type != req.data.obj_type:
AttributeError: 'NoneType' object has no attribute 'obj_type'
```

Steps to replicate (from root of Versa checkout). Assumes a running Versa instance.

1. Set up 
```
$ curl -X PUT 'http://localhost:8080/admin/load_election_data' -H 'Content-Type: application/json' --data-binary '@./test/resources/jetsons.json
```

2. Delete candidate
```
$ curl -X PUT 'http://localhost:8080/contests/con_Orbit_City_Mayoral' -H 'Content-Type: application/json'
```

**Comment by alanyst** [comment] 2023-03-03 13:45
Closing: cannot reproduce with latest changes. I note that the second `curl` command does not use `-X DELETE` and perhaps that was the cause of the original error; but the API response is not 500 but the correct code of 422 Unprocessable Entity.

**Closed as not planned by alanyst** 2023-03-03 13:45 UTC
